name: Firebase Deploy

on:
  push:
    branches:
      - master # Deploy only when changes are pushed to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production # Specify the environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        env:
          CI: false
        run: npm run build

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools@12
          firebase deploy --only hosting --token "$FIREBASE_TOKEN"
